### ISSUE TITLE
Alluxio master starts with failure at first time in Kubernetes

### ISSUE THREAD

**Issue by dxiangaka** [Alluxio/alluxio#10073]
**Alluxio Version:**
Alluxio-2.0.0

**Describe the bug**
When deploying Alluxio cluster in K8s, the master server failed with following error message:
```bash
2019-10-09 15:51:01,836 ERROR AlluxioMaster - Fatal error: Failed to create master process
java.lang.RuntimeException: java.lang.RuntimeException: Journal alluxio.master.journal.raft.RaftJournalSystem@35cabb2a has not been formatted!
	at alluxio.master.AlluxioMasterProcess.<init>(AlluxioMasterProcess.java:117)
	at alluxio.master.FaultTolerantAlluxioMasterProcess.<init>(FaultTolerantAlluxioMasterProcess.java:58)
	at alluxio.master.AlluxioMasterProcess$Factory.create(AlluxioMasterProcess.java:378)
	at alluxio.master.AlluxioMaster.main(AlluxioMaster.java:45)
Caused by: java.lang.RuntimeException: Journal alluxio.master.journal.raft.RaftJournalSystem@35cabb2a has not been formatted!
```

**To Reproduce**
Following steps described in https://docs.alluxio.io/os/user/stable/en/deploy/Running-Alluxio-On-Kubernetes.html to start Alluxio cluster in HA mode with embedded journal setups.

Run command to check log messages
```bash
kubectl logs -f alluxio-master-0 -c alluxio-master
```

**Expected behavior**
The Alluxio master should be formatted at the very first time if it has not been formatted. The option "--no-format" should apply if pod is restarted.

**Urgency**
High priority.

**Additional context**

**Comment by apc999** [comment]
@madanadit @jiacheliu3 can you double check if this issue has been fixed recently in master (2.1.0-SNAPSHOT) branch?

**Comment by jiacheliu3** [comment]
@apc999 The issue has been fixed in 2.1.0-SNAPSHOT. There are template YAML files that users can start from for multi-master environment using embedded journal. And the instructions for setting this up is documentated in the updated in the docs.

@dxiangaka If you look at [Alluxio template embedded journal](https://github.com/Alluxio/alluxio/tree/master/integration/kubernetes/multiMaster-embeddedJournal) this provides a working set of YAML templates to start from. `--no-format` is applied to Alluxio master so this is resolved. 

Specific to 2.0.0, i think the documentation for 2.0 says Embedded Journal was not supported?

**Comment by jiacheliu3** [comment]
I think this issue can be closed because it's fixed in the latest version. What do you think @madanadit ?

**Comment by apc999** [comment]
@madanadit can you point out the fix here and I could close this ticket. In case @dxiangaka still see the issue with nightly build, we could re-open the issue.

**Comment by apc999** [comment]
Close this Issue as confirmed since this has been addressed in 2.1.0-SNAPSHOT and @dxiangaka has a workaround too.
