### ISSUE TITLE
[alluxio-2.0-rc2]workers failed to start if config with multiple value to  dirs.path

### ISSUE THREAD

**Issue by FrankYu** [Alluxio/alluxio#9279]
**Alluxio Version:**
alluxio-2.0-rc2 

**Describe the bug**
workers failed to start if config with multiple value to  dirs.path

**To Reproduce**

config a worker with below configurations, then try to start worker with alluxio-start.sh script 
alluxio.worker.tieredstore.level1.dirs.path=/mnt/ssd1,/mnt/ssd2,/mnt/ssd3

**Expected behavior**

worker should started properly 

**Urgency**
high

**Additional context**

```
#alluxio-start.sh worker Mount
Killed 0 processes on xxx.xx.x
Ramdisk not detected. Mounting...
Formatting RamFS: /mnt/ramdisk (42949672960)
Starting worker @ xxx.xx.x. Logging to /var/log/alluxio/
--- [ FAILED ] The worker @ xxx.xx.x is not serving requests.
--- Printing the log tail for /var/log/alluxio//worker.log
>>> BEGIN
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:host.name=xxx.xx.x
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:java.version=1.8.0_212
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:java.vendor=Oracle Corporation
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:java.class.path=/usr/local/alluxio-2.0.0-RC2/conf/::/usr/local/alluxio-2.0.0-RC2/assembly/alluxio-server-2.0.0-RC2.jar
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:java.library.path=:/usr/local/hadoop-2.7.2/lib/native:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/lib/amd64/server:/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:java.io.tmpdir=/tmp
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:java.compiler=<NA>
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:os.name=Linux
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:os.arch=amd64
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:os.version=5.0.10-1.el7.elrepo.x86_64
2019-06-13 11:28:48,014 INFO  ZooKeeper - Client environment:user.name=root
2019-06-13 11:28:48,015 INFO  ZooKeeper - Client environment:user.home=/root
2019-06-13 11:28:48,015 INFO  ZooKeeper - Client environment:user.dir=/root
2019-06-13 11:28:48,015 INFO  ZooKeeper - Initiating client connection, connectString=AA:2181,BB:2181,CC:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@3c0f93f1
2019-06-13 11:28:48,032 INFO  ClientCnxn - Opening socket connection to server xxx.xx.x/xxx.xx.x:2181. Will not attempt to authenticate using SASL (unknown error)
2019-06-13 11:28:48,033 INFO  CuratorFrameworkImpl - Default schema
2019-06-13 11:28:48,038 INFO  ClientCnxn - Socket connection established to xxx.xx.x/xxx.xx.x:2181, initiating session
2019-06-13 11:28:48,043 INFO  ClientCnxn - Session establishment complete on server xxx.xx.x/xxx.xx.x:2181, sessionid = 0x1000000f43a0030, negotiated timeout = 40000
2019-06-13 11:28:48,050 INFO  ConnectionStateManager - State change: CONNECTED
2019-06-13 11:28:48,505 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master xxx.xx.x/xxx.xx.x:19998
2019-06-13 11:28:48,510 INFO  ConfigurationUtils - Alluxio client (version 2.0.0-RC2) is trying to load cluster level configurations
2019-06-13 11:28:48,528 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
2019-06-13 11:28:48,547 INFO  TieredIdentityFactory - Initialized tiered identity TieredIdentity(node=xxx.xx.x, rack=null)
2019-06-13 11:28:48,748 INFO  BlockWorkerFactory - Creating alluxio.worker.block.BlockWorker
2019-06-13 11:28:48,748 INFO  FileSystemWorkerFactory - Creating alluxio.worker.file.FileSystemWorker
2019-06-13 11:28:48,776 INFO  StorageDir - Folder /mnt/ramdisk/alluxioworker was created!
2019-06-13 11:28:48,791 WARN  StorageTier - Failed to verify memory capacity
2019-06-13 11:28:48,793 INFO  StorageDir - Folder /mnt/ssd1/alluxioworker was created!
<<< EOF
--- Printing the log tail for /var/log/alluxio//worker.out
>>> BEGIN
	at alluxio.worker.WorkerProcess$Factory.create(WorkerProcess.java:38)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:68)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at alluxio.util.CommonUtils.invokeAll(CommonUtils.java:493)
	at alluxio.worker.AlluxioWorkerProcess.<init>(AlluxioWorkerProcess.java:118)
	... 3 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at alluxio.worker.block.meta.StorageTier.initStorageTier(StorageTier.java:95)
	at alluxio.worker.block.meta.StorageTier.newStorageTier(StorageTier.java:186)
	at alluxio.worker.block.BlockMetadataManager.<init>(BlockMetadataManager.java:68)
	at alluxio.worker.block.BlockMetadataManager.createBlockMetadataManager(BlockMetadataManager.java:83)
	at alluxio.worker.block.TieredBlockStore.<init>(TieredBlockStore.java:126)
	at alluxio.worker.block.DefaultBlockWorker.<init>(DefaultBlockWorker.java:134)
	at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:43)
	at alluxio.worker.block.BlockWorkerFactory.create(BlockWorkerFactory.java:26)
	at alluxio.worker.AlluxioWorkerProcess.lambda$new$0(AlluxioWorkerProcess.java:110)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Heap
 par new generation   total 613440K, used 229045K [0x00000005c0000000, 0x00000005e9990000, 0x00000005e9990000)
  eden space 545344K,  42% used [0x00000005c0000000, 0x00000005cdfad660, 0x00000005e1490000)
  from space 68096K,   0% used [0x00000005e1490000, 0x00000005e1490000, 0x00000005e5710000)
  to   space 68096K,   0% used [0x00000005e5710000, 0x00000005e5710000, 0x00000005e9990000)
 concurrent mark-sweep generation total 3512768K, used 0K [0x00000005e9990000, 0x00000006c0000000, 0x00000007c0000000)
 Metaspace       used 21897K, capacity 22156K, committed 22292K, reserved 1069056K
  class space    used 2610K, capacity 2704K, committed 2760K, reserved 1048576K
<<< EOF
```

**Comment by ns1123** [comment]
Hi Frank,

Do you have a tiered store configured for level0? Our indices start with 0 so changing the property to alluxio.worker.tieredstore.level0.dirs.path should fix it. To have two tiers, you need to set alluxio.worker.tieredstore.levels=2. Then you could set alluxio.worker.tieredstore.level1.dirs.path to configure your second tier.

**Comment by FrankYu** [comment]
> Hi Frank,
> 
> Do you have a tiered store configured for level0? Our indices start with 0 so changing the property to alluxio.worker.tieredstore.level0.dirs.path should fix it. To have two tiers, you need to set alluxio.worker.tieredstore.levels=2. Then you could set alluxio.worker.tieredstore.level1.dirs.path to configure your second tier.

yes, I have store 2 tieredstore. and level0 is mem. level1 is SSD, with three ssd. it is easy to reproduce with 2.0, and works well with 1.8.2

**Comment by ns1123** [comment]
Hi Frank,

Looking at the code, we have added a new field for medium type as an addition to the TieredStore feature. The property is listed below. The error you are seeing is due to a lack of bounds checking on our side, however, if you add the storage medium property for your SSD tier, your issue should be resolved. In the meantime, we will look into how to resolve this issue in the future.

Property: alluxio.worker.tieredstore.level1.dirs.mediumtype=SSD,SSD,SSD

Thanks,
Nakkul

**Comment by yuzhu** [comment]
This issue is fixed in PR #9311 .

**Comment by FrankYu** [comment]
> Hi Frank,
> 
> Looking at the code, we have added a new field for medium type as an addition to the TieredStore feature. The property is listed below. The error you are seeing is due to a lack of bounds checking on our side, however, if you add the storage medium property for your SSD tier, your issue should be resolved. In the meantime, we will look into how to resolve this issue in the future.
> 
> Property: alluxio.worker.tieredstore.level1.dirs.mediumtype=SSD,SSD,SSD
> 
> Thanks,
> Nakkul

Hi Nakkul, 

 my config is as below now, the worker still can't be started
`
alluxio.worker.tieredstore.levels=2
alluxio.worker.tieredstore.level0.alias=MEM
alluxio.worker.tieredstore.level0.dirs.path=/mnt/ramdisk
alluxio.worker.tieredstore.level0.dirs.quota=20GB
alluxio.worker.tieredstore.level0.watermark.high.ratio=0.95
alluxio.worker.tieredstore.level0.watermark.low.ratio=0.5
alluxio.worker.tieredstore.level1.alias=SSD
alluxio.worker.tieredstore.level1.dirs.mediumtype=SSD,SSD,SSD
alluxio.worker.tieredstore.level1.dirs.path=/mnt/ssd1/,/mnt/ssd2/,/mnt/ssd3
alluxio.worker.tieredstore.level1.dirs.quota=745GB,745GB,745GB
alluxio.worker.tieredstore.level1.watermark.high.ratio=0.95
alluxio.worker.tieredstore.level1.watermark.low.ratio=0.5
`
errors: 
`2019-06-20 13:24:58,123 INFO  ConfigurationUtils - Alluxio client (version 2.0.0-RC3) is trying to load cluster level configurations
2019-06-20 13:24:58,125 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
2019-06-20 13:24:58,130 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
2019-06-20 13:24:58,130 INFO  ConfigurationUtils - Alluxio client has loaded cluster level configurations
2019-06-20 13:24:58,254 ERROR ProcessUtils - Uncaught exception while running Alluxio worker, stopping it and exiting.
alluxio.exception.status.UnknownException
	at alluxio.exception.status.AlluxioStatusException.from(AlluxioStatusException.java:154)
	at alluxio.exception.status.AlluxioStatusException.fromStatusRuntimeException(AlluxioStatusException.java:209)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:371)
	at alluxio.AbstractClient.retryRPC(AbstractClient.java:331)
	at alluxio.worker.block.BlockMasterClient.register(BlockMasterClient.java:222)
	at alluxio.worker.block.BlockMasterSync.registerWithMaster(BlockMasterSync.java:106)
	at alluxio.worker.block.BlockMasterSync.<init>(BlockMasterSync.java:93)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:214)
	at alluxio.worker.block.DefaultBlockWorker.start(DefaultBlockWorker.java:77)
	at alluxio.Registry.start(Registry.java:131)
	at alluxio.worker.AlluxioWorkerProcess.startWorkers(AlluxioWorkerProcess.java:283)
	at alluxio.worker.AlluxioWorkerProcess.start(AlluxioWorkerProcess.java:235)
	at alluxio.ProcessUtils.run(ProcessUtils.java:35)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:69)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)
	at alluxio.grpc.BlockMasterWorkerServiceGrpc$BlockMasterWorkerServiceBlockingStub.registerWorker(BlockMasterWorkerServiceGrpc.java:477)
	at alluxio.worker.block.BlockMasterClient.lambda$register$6(BlockMasterClient.java:223)
	at alluxio.AbstractClient.retryRPCInternal(AbstractClient.java:369)
	... 11 more
2019-06-20 13:24:58,259 INFO  GrpcDataServer - Shutting down RPC Server at 0.0.0.0/0.0.0.0:29999.
2019-06-20 13:25:00,965 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master kscpu007.hogpu.cc/10.10.216.8:19998
2019-06-20 13:25:00,965 INFO  ConfigurationUtils - Alluxio client (version 2.0.0-RC3) is trying to load path level configurations
2019-06-20 13:25:00,965 INFO  ConfigurationUtils - Alluxio client has loaded path level configurations
2019-06-20 13:25:01,080 INFO  ConfigurationUtils - Alluxio client has loaded configuration from meta master kscpu007.hogpu.cc/10.10.216.8:19998
2019-06-20 13:25:01,080 INFO  ConfigurationUtils - Alluxio client (version 2.0.0-RC3) is trying to load path level configurations
2019-06-20 13:25:01,080 INFO  ConfigurationUtils - Alluxio client has loaded path level configurations
2019-06-20 13:25:02,677 INFO  GrpcDataServer - Shutting down RPC Server at /usr/local/alluxio/run/d3316fcf-e628-4d40-8190-706dad0ec086.
2019-06-20 13:25:07,100 ERROR ProcessUtils - Uncaught exception while stopping Alluxio worker, simply exiting.
java.lang.NullPointerException
	at alluxio.worker.block.DefaultBlockWorker.stop(DefaultBlockWorker.java:263)
	at alluxio.Registry.stop(Registry.java:148)
	at alluxio.worker.AlluxioWorkerProcess.stopWorkers(AlluxioWorkerProcess.java:287)
	at alluxio.worker.AlluxioWorkerProcess.stop(AlluxioWorkerProcess.java:274)
	at alluxio.ProcessUtils.run(ProcessUtils.java:41)
	at alluxio.worker.AlluxioWorker.main(AlluxioWorker.java:69)`

**Comment by yuzhu** [comment]
@FrankYu Thanks for trying out our RC release. 

The current log masks the root cause exception unfortunately. Have you built Alluxio from the source?  There are some instructions [here](https://docs.alluxio.io/os/user/stable/en/contributor/Building-Alluxio-From-Source.html)
What you can do is check out either the latest master and try it.  or checkout one of the Rc releases and apply the change in #9343. Compile it and run it.  It will give us more useful logging and we can try to debug from there.

**Comment by rastogiasr** [comment]
Closing this issue, reopen if still an issue.

**Comment by gpang** [comment]
This was an issue with worker registration. This was fixed by this PR: https://github.com/Alluxio/alluxio/pull/9517
